### ISSUE TITLE
Document the task system.

### ISSUE THREAD

**Issue by automatthew** [pandastrike/jsck#79]
e.g.

    coffee tasks/build/docs.coffee

**Comment by gilesbowkett** [comment]
I think we should not use `pfm` in this. First, it causes a weird extra dependency, which (obviously) is not yet documented. As a result, whenever we get a PR, it edits `README.md` in ignorance of the existence of `docs/README.pfm.md`.

Second, I've seen lots of places where that went stale. Just now I tried to rev it back up again, and got this:

```
<retina:giles> ~/code/panda/jsck pfm-doc
 ¯\_(ツ)_/¯ coffee tasks/build/docs.coffee 
pfm doc/README.pfm.md -o README.md
pfm doc/tests.pfm.md -o doc/tests.md
/Users/giles/.rbenv/versions/2.0.0-p0/gemsets/jsck-pfm-081215/gems/pfm-0.1.0/lib/pfm.rb:35:in `initialize': No such file or directory - /Users/giles/code/panda/jsck/test/JSON-Schema-Test-Suite/tests/draft4/items.json (Errno::ENOENT)
	from /Users/giles/.rbenv/versions/2.0.0-p0/gemsets/jsck-pfm-081215/gems/pfm-0.1.0/lib/pfm.rb:35:in `open'
	from /Users/giles/.rbenv/versions/2.0.0-p0/gemsets/jsck-pfm-081215/gems/pfm-0.1.0/lib/pfm.rb:35:in `block in process'
	from /Users/giles/.rbenv/versions/2.0.0-p0/gemsets/jsck-pfm-081215/gems/pfm-0.1.0/lib/pfm.rb:21:in `each'
	from /Users/giles/.rbenv/versions/2.0.0-p0/gemsets/jsck-pfm-081215/gems/pfm-0.1.0/lib/pfm.rb:21:in `process'
	from /Users/giles/.rbenv/versions/2.0.0-p0/gemsets/jsck-pfm-081215/gems/pfm-0.1.0/lib/pfm.rb:7:in `process'
	from /Users/giles/.rbenv/versions/2.0.0-p0/gemsets/jsck-pfm-081215/gems/pfm-0.1.0/bin/pfm:23:in `<top (required)>'
	from /Users/giles/.rbenv/versions/2.0.0-p0/gemsets/jsck-pfm-081215/bin/pfm:23:in `load'
	from /Users/giles/.rbenv/versions/2.0.0-p0/gemsets/jsck-pfm-081215/bin/pfm:23:in `<main>'
pfm doc/benchmarks.pfm.md -o doc/benchmarks.md
```

That traces to `doc/tests.pfm.md`:

```
 24 JSCK includes the official test suite as a git submodule at
 25 `test/JSON-Schema-Test-Suite`. Running `coffee tasks/update` will initialize
 26 and/or update the submodule.
 27 
 28 
 29 As a concrete example, here is the first case for the "items" attribute in Draft 4:
 30 
 31 ```test/JSON-Schema-Test-Suite/tests/draft4/items.json#L2-24```
```

It's trying to incorporate code from a file which is missing. I tried to summon the missing file:

```
<retina:giles> ~/code/panda/jsck pfm-doc
 ¯\_(ツ)_/¯ git submodule update --init
Submodule 'test/JSON-Schema-Test-Suite' (git@github.com:automatthew/JSON-Schema-Test-Suite.git) registered for path 'test/JSON-Schema-Test-Suite'
Submodule 'test/json-schema' (git@github.com:json-schema/json-schema.git) registered for path 'test/json-schema'
Cloning into 'test/JSON-Schema-Test-Suite'...
ERROR: Repository not found.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Clone of 'git@github.com:automatthew/JSON-Schema-Test-Suite.git' into submodule path 'test/JSON-Schema-Test-Suite' failed
```

But it looks as if it was linked to a personal repo of yours, which has now been deleted.

There's a recursive link rot risk here. First, any use of `git submodule` depends on the submodule existing. Second, if a file changes, and a reference to it in a `pfm` doc doesn't change accordingly, we can't build the `pfm` doc any more.

I've got a PR I want to look at today. If I accept it, I broaden the gap between `README.md` and `docs/README.pfm.md`. If I don't want to broaden that gap, I have to fix issues unrelated to the PR.
